In [1]:
import numpy as np
import pandas as pd

In [2]:
def euclideanDistance(x1,x2):
  return np.sqrt(np.sum((x1-x2)**2))

In [3]:
class KNN:
  def __init__(self,k):
    self.k=k

  def fit(self,x,y):
    self.xtrain=x
    self.ytrain=y
  
  def predict(self,x):
    ypred=[]
    for i in x:
      distances=[euclideanDistance(i,x_train) for x_train in self.xtrain]
      k_indices=np.argsort(distances)[:self.k]
      k_neighbours=[self.ytrain[i] for i in k_indices]
      ypred.append(max(k_neighbours,key=k_neighbours.count))
    return np.array(ypred)

In [4]:
from google.colab import drive
drive.mount('/content/drive')
path='/content/drive/MyDrive/data.csv'
df=pd.read_csv(path)
df

Mounted at /content/drive

   height  weight  age  gender
0     5.9     160   25       0
1     5.7     140   23       0
2     5.8     150   27       0
3     5.6     135   22       0
4     5.5     125   21       0
5     6.1     175   30       1
6     5.9     165   28       1
7     5.8     155   29       1
8     5.7     150   26       0
9     5.6     140   24       0

In [5]:
#splitting test and train data
trainData = df[:8]
testData = df[8:]

print("training data")
print(trainData)
print("testing data")
print(testData)

training data
   height  weight  age  gender
0     5.9     160   25       0
1     5.7     140   23       0
2     5.8     150   27       0
3     5.6     135   22       0
4     5.5     125   21       0
5     6.1     175   30       1
6     5.9     165   28       1
7     5.8     155   29       1
testing data
   height  weight  age  gender
8     5.7     150   26       0
9     5.6     140   24       0

In [6]:
trainx= trainData.iloc[:,:3].values
trainy= trainData.iloc[:,3].values

testx=testData.iloc[:,:3].values
testy= testData.iloc[:,3].values

In [7]:
knn = KNN(3)
knn.fit(trainx,trainy)

predict = knn.predict(testx)